// Generated by CoffeeScript 1.3.3
var Responder, ZMQ,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

ZMQ = require("zmq");

module.exports = Responder = (function() {

  function Responder(options) {
    this.options = options != null ? options : {};
    this._runTask = __bind(this._runTask, this);

    this._message = __bind(this._message, this);

    this.workerClasses = {};
    this._connect();
    this.registerWorker('Reverse', require('./workers/reverse'));
  }

  Responder.prototype.close = function() {
    return this.socket.close();
  };

  Responder.prototype.registerWorker = function(name, workerClass) {
    return this.workerClasses[name] = workerClass;
  };

  Responder.prototype._connect = function() {
    var endpoint;
    endpoint = this.options.dealer || "ipc:///tmp/tern.reqres-dealer";
    this.socket = ZMQ.socket("rep");
    this.socket.on("message", this._message);
    return this.socket.connect(endpoint);
  };

  Responder.prototype._message = function(payload) {
    var task,
      _this = this;
    task = JSON.parse(payload);
    return this._runTask(task, function(err, data) {
      var retPayload;
      retPayload = err != null ? JSON.stringify({
        id: task.id,
        response: "failed",
        data: err.toString()
      }) : JSON.stringify({
        id: task.id,
        response: "completed",
        data: data
      });
      return _this.socket.send(retPayload);
    });
  };

  Responder.prototype._runTask = function(task, next) {
    var instance, workerClass;
    try {
      workerClass = this.workerClasses[task.request];
      if (workerClass == null) {
        throw new Error("Unknown task " + (JSON.stringify(task)));
      }
      instance = new workerClass(this);
      return instance.run(task.data, next);
    } catch (err) {
      return next(err);
    }
  };

  return Responder;

})();
