// Generated by CoffeeScript 1.3.3
var Config, EventEmitter,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

EventEmitter = require('events').EventEmitter;

Config = (function(_super) {

  __extends(Config, _super);

  function Config(path) {
    this.path = path;
  }

  return Config;

})(EventEmitter);

module.exports = Config;
