// Generated by CoffeeScript 1.3.3
var deepEquals;

deepEquals = function(obj1, obj2) {
  var p, x1, x2, _ref, _ref1;
  x1 = JSON.parse(JSON.stringify(obj1));
  x2 = JSON.parse(JSON.stringify(obj2));
  if (((_ref = typeof x1) === 'string' || _ref === 'number') && ((_ref1 = typeof x2) === 'string' || _ref1 === 'number')) {
    return x1 === x2;
  }
  p = null;
  for (p in x1) {
    if (typeof x2[p] === 'undefined') {
      return false;
    }
  }
  for (p in x1) {
    if (x1[p]) {
      switch (typeof x1[p]) {
        case 'object':
          if (!deepEquals(x1[p], x2[p])) {
            return false;
          }
          break;
        case 'function':
          if (typeof x2[p] === 'undefined' || (p !== 'equals' && x1[p].toString() !== x2[p].toString())) {
            return false;
          }
          break;
        default:
          if (x1[p] !== x2[p]) {
            return false;
          }
      }
    } else {
      if (x2[p]) {
        return false;
      }
    }
  }
  for (p in x2) {
    if (typeof x1[p] === 'undefined') {
      return false;
    }
  }
  return true;
};

module.exports.deepEquals = deepEquals;
