// Generated by CoffeeScript 1.3.3
var Assert, MediaFile, mediaDeleter;

MediaFile = require('../models/media_file_mod');

Assert = require('assert');

/*
  Media delete middleware
*/


mediaDeleter = function(req, res, next) {
  Assert.equal(req.method, 'DELETE');
  Assert.ok(req._tern);
  Assert.ok(req._tern.user_id);
  Assert.ok(req._tern.media_id);
  return MediaFile.unlink(req._tern.media_id, function(err, numberOfRemovedDocs) {
    if (err != null) {
      return next(err);
    }
    if (numberOfRemovedDocs > 0) {
      return res.send(200);
    } else {
      return res.send(404);
    }
  });
};

module.exports = mediaDeleter;
