// Generated by CoffeeScript 1.3.3
var exports, send_media;

send_media = require('./send_media');

exports = module.exports = function(options) {
  options = options != null ? options : {};
  return function(req, res, next) {
    var error, _ref, _ref1;
    if ((_ref = req.method) !== 'GET' && _ref !== 'HEAD') {
      next;

    }
    error = function(err) {
      if (err.status === 404) {
        return next();
      } else {
        return next(err);
      }
    };
    return send_media(req).maxage((_ref1 = options.maxAge) != null ? _ref1 : 0).on('error', error).pipe(res);
  };
};
