// Generated by CoffeeScript 1.3.3
var IPUtils, argv;

IPUtils = require('tern.ip_utils');

argv = require('optimist')["default"]('host', '*')["default"]('res_port', 21001)["default"]('pub_port', 21002).usage('Usage: $0 --host [192.168.1.10] --res_port [21001] --pub_port [21002]').argv;

module.exports.getEndpoints = function() {
  var errMessage, pubEndpoint, resEndpoint, _ref, _ref1;
  errMessage = null;
  if (argv.host !== '*' && IPUtils.verify(argv.host) !== true) {
    errMessage = 'Bad parameter of --host';
  } else {
    if (!((1024 <= (_ref = argv.res_port) && _ref <= 65535))) {
      errMessage('Bad parameter of --res_port');
    } else {
      if (!((1024 <= (_ref1 = argv.pub_port) && _ref1 <= 65535))) {
        errMessage('Bad parameter of --pub_port');
      } else {
        if (argv.res_port === argv.pub_port) {
          errMessage('Bad parameter: --res_port can not equal --pub_port');
        } else {
          resEndpoint = "tcp://" + argv.host + ":" + argv.res_port;
          pubEndpoint = "tcp://" + argv.host + ":" + argv.pub_port;
          return {
            host: argv.host,
            resEndpoint: resEndpoint,
            pubEndpoint: pubEndpoint
          };
        }
      }
    }
  }
  throw new Error(errMessage);
};
