// Generated by CoffeeScript 1.3.3
var Argvs, Path, Server, host, options, pubEndpoint, resEndpoint, server, _ref;

process.title = 'Tern.GlobalConfig';

Server = require('tern.central_config').Server;

Path = require('path');

Argvs = require('./arguments_check');

try {
  _ref = Argvs.getEndpoints(), host = _ref.host, resEndpoint = _ref.resEndpoint, pubEndpoint = _ref.pubEndpoint;
} catch (err) {
  console.error(err.toString());
  return;
}

console.log(require('tern.logo').GlobalConfig('0.1'));

options = {
  configFilename: Path.resolve(__dirname, '../config_file/global_config.coffee'),
  responder: resEndpoint,
  publisher: pubEndpoint
};

server = new Server(options);
