// Generated by CoffeeScript 1.3.3
var IPUtils, Path, Server, argv, options, pubEndpoint, resEndpoint, server, _ref, _ref1;

IPUtils = require('tern.ip_utils');

Server = require('tern.central_config').Server;

Path = require('path');

argv = require('optimist')["default"]('host', '*')["default"]('res_port', 21001)["default"]('pub_port', 21002).usage('Usage: $0 --host [192.168.1.10] --res_port [21001] --pub_port [21002]').argv;

if (argv.host !== '*' && IPUtils.verify(argv.host) !== true) {
  console.error('Bad parameter of --host');
} else {
  if (!((1024 <= (_ref = argv.res_port) && _ref <= 65535))) {
    console.error('Bad parameter of --res_port');
  } else {
    if (!((1024 <= (_ref1 = argv.pub_port) && _ref1 <= 65535))) {
      console.error('Bad parameter of --pub_port');
    } else {
      if (argv.res_port === argv.pub_port) {
        console.error('Bad parameter: --res_port can not equal --pub_port');
      } else {
        console.log(require('tern.logo')('Config. 0.1'));
        resEndpoint = "tcp://" + argv.host + ":" + argv.res_port;
        pubEndpoint = "tcp://" + argv.host + ":" + argv.pub_port;
        options = {
          configFilename: Path.resolve(__dirname, '../config_file/config.coffee'),
          responder: resEndpoint,
          publisher: pubEndpoint
        };
        server = new Server(options);
      }
    }
  }
}
