// Generated by CoffeeScript 1.3.3
var Broker, Domain, Log;

Log = require('tern.logger');

Broker = require('tern.zmq_reqres').Broker;

Domain = require('domain');

module.exports.start = function(argv) {
  var serverDomain;
  serverDomain = Domain.create();
  serverDomain.on('error', function(err) {
    return Log.error("Uncaught error on Auth. ZMQ Server: " + (err.toString()) + "\r\n" + err.stack);
  });
  return serverDomain.run(function() {
    var broker;
    broker = new Broker(argv);
    Log.notice("Auth. ZMQ Server started: [router]:" + argv.router + " and [dealer]:" + argv.dealer);
    return require('./zmq_workers/token_auth').register(argv);
  });
};
