// Generated by CoffeeScript 1.3.3
var Utils;

Utils = require('tern.utils');

module.exports.DevicesKey = function(user_id) {
  return Utils.pathJoin('users', user_id, 'devices');
};

module.exports.MemosKey = function(user_id, mid) {
  return Utils.pathJoin('users', user_id, 'memos', mid);
};

module.exports.MemosBase = function(user_id) {
  return Utils.pathJoin('users', user_id, 'memos');
};

module.exports.MemosChangeLogKey = function(user_id, device_id) {
  return Utils.pathJoin('users', user_id, 'changelog', 'memos', device_id);
};

module.exports.TidMidBaseKey = function(user_id) {
  return Utils.pathJoin('users', user_id, 'tid_mid');
};

module.exports.TagsKey = function(user_id, tid) {
  return Utils.pathJoin('users', user_id, 'tags', tid);
};

module.exports.TagsBase = function(user_id) {
  return Utils.pathJoin('users', user_id, 'tags');
};

module.exports.TagKeyMappingBase = function(user_id) {
  return Utils.pathJoin('users', user_id, 'tagkey_to_tid');
};

module.exports.TagsChangeLogKey = function(user_id, device_id) {
  return Utils.pathJoin('users', user_id, 'changelog', 'tags', device_id);
};
