// Generated by CoffeeScript 1.3.3
var Broker, Domain, Log;

Log = require('tern.logger');

Broker = require('tern.queue').Broker;

Domain = require('domain');

module.exports.start = function(argv) {
  var serverDomain;
  serverDomain = Domain.create();
  serverDomain.on('error', function(err) {
    return Log.error("Uncaught error on Auto Tagging Service: " + (err.toString()) + "\r\n" + err.stack);
  });
  return serverDomain.run(function() {
    var broker;
    broker = new Broker(argv);
    return Log.notice("Auto Tagging Service started: [router]:" + argv.router + " and [dealer]:" + argv.dealer);
  });
};
