// Generated by CoffeeScript 1.3.3
var createError;

createError = function(message, name) {
  var err;
  err = new Error(message);
  err.name = name;
  return err;
};

/*
# ArgumentException
*/


exports.ArgumentException = function(message) {
  return createError(message, "ArgumentException");
};

exports.ArgumentNullException = function(message) {
  return createError(message, "ArgumentNullException");
};

exports.ArgumentLengthException = function(message) {
  return createError(message, "ArgumentLengthException");
};

exports.ArgumentInRangeException = function(message) {
  return createError(message, "ArgumentInRangeException");
};

exports.ArgumentInRangeException = function(message) {
  return createError(message, "ArgumentInRangeException");
};

exports.ArgumentUnsupportedException = function(message) {
  return createError(message, "ArgumentUnsupportedException");
};

/*
# Resource
*/


exports.ResourceExistsException = function(message) {
  return createError(message, "ResourceExistsException");
};

exports.ResourceDoesNotExistException = function(message) {
  return createError(message, "ResourceDoesNotExistException");
};

/*
# Timeout
*/


exports.TimeoutException = function(message) {
  return createError(message, "TimeoutException");
};
