// Generated by CoffeeScript 1.3.3
var BrokersHelper, Datazones, argv, globalConfigOpts, zoneConfigOpts;

BrokersHelper = require('tern.central_config').BrokersHelper;

Datazones = require('tern.data_zones');

argv = require('optimist')["default"]('g_req', 'tcp://127.0.0.1:21001')["default"]('g_sub', 'tcp://127.0.0.1:21002')["default"]('z_req', 'tcp://127.0.0.1:21101')["default"]('z_sub', 'tcp://127.0.0.1:21102').argv;

globalConfigOpts = {
  requester: argv.g_req,
  subscriber: argv.g_sub
};

zoneConfigOpts = {
  requester: argv.z_req,
  subscriber: argv.z_sub
};

module.exports.init = function(serviceType, next) {
  return BrokersHelper.init(globalConfigOpts, zoneConfigOpts, function() {
    var dataZone;
    dataZone = Datazones.currentDataZone();
    switch (serviceType) {
      case 'WebSocket':
        argv = Datazones.getWebSocketBind(dataZone);
        break;
      case 'Media':
        argv = Datazones.getMediaBind(dataZone);
        break;
      case 'ZMQ':
        argv = Datazones.getZMQBind(dataZone);
        break;
      default:
        (next != null) && next(new Error("Unsupported serviceType"));
    }
    return (next != null) && next(null, argv);
  });
};
