// Generated by CoffeeScript 1.3.3
var BrokersHelper, ConfigGetter;

process.title = 'Tern.DataQueues';

BrokersHelper = require('tern.central_config').BrokersHelper;

ConfigGetter = require('./config_getter');

ConfigGetter.init('DataQueues', function(err, argv) {
  var Broker, Log, broker, options, value, zone, _ref, _results;
  if (err != null) {
    console.error(err.toString(), err.stack);
  }
  console.log(require('tern.logo').DataQueues('0.1'));
  Log = require('tern.logger');
  Broker = require('tern.queue').Broker;
  broker = null;
  options = {};
  _ref = argv.queues;
  _results = [];
  for (zone in _ref) {
    value = _ref[zone];
    options.router = BrokersHelper.getEndpointFromConfigValue(value.router.bind);
    options.dealer = BrokersHelper.getEndpointFromConfigValue(value.dealer.bind);
    options.from = argv.current;
    options.to = zone;
    broker = new Broker(options);
    options = broker.options;
    _results.push(Log.notice("Data Queues: " + options.from + " to " + options.to + " - [router]:" + options.router + " and [dealer]:" + options.dealer));
  }
  return _results;
});
