// Generated by CoffeeScript 1.3.3
var ConfigGetter;

process.title = 'Tern.MediaQueues';

ConfigGetter = require('./config_getter');

ConfigGetter.init('MediaQueues', function(err, argv) {
  var Broker, Log, broker, host, options, port, value, zone, _ref, _ref1, _ref2, _results;
  if (err != null) {
    console.error(err.toString(), err.stack);
  }
  console.log(require('tern.logo').MediaQueues('0.1'));
  Log = require('tern.logger');
  Broker = require('tern.queue').Broker;
  broker = null;
  options = {};
  _ref = argv.queues;
  _results = [];
  for (zone in _ref) {
    value = _ref[zone];
    _ref1 = value.router.bind, host = _ref1.host, port = _ref1.port;
    options.router = "tcp://" + host + ":" + port;
    _ref2 = value.dealer.bind, host = _ref2.host, port = _ref2.port;
    options.dealer = "tcp://" + host + ":" + port;
    options.from = argv.current;
    options.to = zone;
    broker = new Broker(options);
    options = broker.options;
    _results.push(Log.notice("Media Queues: " + options.from + " to " + options.to + " - [router]:" + options.router + " and [dealer]:" + options.dealer));
  }
  return _results;
});
