// Generated by CoffeeScript 1.3.3
var ConfigGetter;

process.title = 'Tern.Queue';

ConfigGetter = require('./config_getter');

ConfigGetter.init('Queue', function(err, argv) {
  var Broker, Log, broker, host, options, port, _ref, _ref1;
  if (err != null) {
    console.error(err.toString(), err.stack);
  }
  console.log(require('tern.logo').Queue('0.1'));
  Log = require('tern.logger');
  options = {};
  _ref = argv.router.bind, host = _ref.host, port = _ref.port;
  options.router = "tcp://" + host + ":" + port;
  _ref1 = argv.dealer.bind, host = _ref1.host, port = _ref1.port;
  options.dealer = "tcp://" + host + ":" + port;
  Broker = require('tern.queue').Broker;
  try {
    broker = new Broker(options);
    return broker.on('bind', function() {
      return Log.notice("Queue Server is listening on [router]:" + options.router + " and [dealer]:" + options.dealer);
    });
  } catch (err) {
    return console.error(err);
  }
  /*
    Log             = require 'tern.logger'
    Perf            = require 'tern.perf_counter'
    Utils           = require 'tern.utils'
  */

});
