// Generated by CoffeeScript 1.3.3
var Broker;

Broker = require('tern.central_config').Broker;

module.exports.init = function(next) {
  var globalBroker, globalConfigOpts, zoneBroker, zoneConfigOpts;
  if ((global.globalBroker != null) || (global.zoneBroker != null)) {
    return next && next();
  } else {
    console.log('initializing config');
    globalConfigOpts = {
      requester: 'tcp://127.0.0.1:21001',
      subscriber: 'tcp://127.0.0.1:21002'
    };
    zoneConfigOpts = {
      requester: 'tcp://127.0.0.1:21101',
      subscriber: 'tcp://127.0.0.1:21102'
    };
    globalBroker = new Broker(globalConfigOpts);
    zoneBroker = new Broker(zoneConfigOpts);
    process.on('exit', function() {
      delete global.globalBroker;
      return delete global.zoneBroker;
    });
    return globalBroker.init(function(configFile) {
      global.globalBroker = globalBroker;
      return zoneBroker.init(function(configFile) {
        global.zoneBroker = zoneBroker;
        return next && next();
      });
    });
  }
};

module.exports.initSync = function() {
  return module.exports.init();
};
