// Generated by CoffeeScript 1.3.3
var PATH_CHAR, TAG_SPLIT_CHAR, pathJoin,
  __slice = [].slice;

PATH_CHAR = '/';

TAG_SPLIT_CHAR = ':';

pathJoin = function() {
  var args;
  args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  return args.join(PATH_CHAR);
};

/*
  Keys used in Central Auth.
*/


module.exports.AccountKey = function(user_id) {
  return pathJoin('users', user_id);
};

module.exports.AccountBaseKey = function() {
  return 'users';
};

module.exports.EmailToUserIDKey = function(email) {
  return pathJoin('users', email);
};

module.exports.EmailToUserIDBaseKey = function() {
  return 'users';
};

module.exports.EmailTokenToUserObjKeyBase = function() {
  return pathJoin('email', 'tokens');
};

module.exports.EmailTokenToUserObjKey = function(token) {
  return pathJoin(module.exports.EmailTokenToUserObjKeyBase(), token);
};

module.exports.EmailToTokenKey = function(email) {
  return pathJoin('email', 'email', email);
};

/*
  Keys used in Data Zone
*/


module.exports.DevicesKey = function(user_id) {
  return pathJoin('users', user_id, 'devices');
};

module.exports.MemosKey = function(user_id, mid) {
  return pathJoin('users', user_id, 'memos', mid);
};

module.exports.MemosBase = function(user_id) {
  return pathJoin('users', user_id, 'memos');
};

module.exports.MemosChangeLogKey = function(user_id, device_id) {
  return pathJoin('users', user_id, 'changelog', 'memos', device_id);
};

module.exports.TidMidBaseKey = function(user_id) {
  return pathJoin('users', user_id, 'tid_mid');
};

module.exports.TagsKey = function(user_id, tid) {
  return pathJoin('users', user_id, 'tags', tid);
};

module.exports.TagsBase = function(user_id) {
  return pathJoin('users', user_id, 'tags');
};

module.exports.TagKeyMappingBase = function(user_id) {
  return pathJoin('users', user_id, 'tagkey_to_tid');
};

module.exports.TagsChangeLogKey = function(user_id, device_id) {
  return pathJoin('users', user_id, 'changelog', 'tags', device_id);
};
