// Generated by CoffeeScript 1.3.3
var BrokersHelper, configObject, currentDataZone, currentObj, dataZones, init;

BrokersHelper = require('tern.central_config').BrokersHelper;

configObject = null;

dataZones = null;

currentObj = null;

currentDataZone = '';

init = function() {
  currentObj = BrokersHelper.getConfig('dataZone');
  if (currentObj != null) {
    currentDataZone = currentObj.value;
    currentObj.on('changed', function(oldValue, newValue) {
      console.log("current datazone config changed from '" + oldValue + "' to '" + newValue + "'");
      return currentDataZone = newValue;
    });
  } else {
    throw new Error("Can not get 'dataZone' from config brokers");
  }
  configObject = BrokersHelper.getConfig('dataZones');
  if (configObject != null) {
    dataZones = configObject.value;
    return configObject.on('changed', function(oldValue, newValue) {
      console.log('dataZones config changed');
      return dataZones = newValue;
    });
  } else {
    throw new Error("Can not get 'dataZones' from config brokers");
  }
};

module.exports.currentDataZone = function() {
  if (currentObj == null) {
    init();
  }
  console.log('currentDataZone', currentDataZone);
  return currentDataZone;
};

module.exports.get = function(datazone) {
  if (configObject == null) {
    init();
  }
  return dataZones[datazone];
};

module.exports.getWebSocketBind = function(datazone) {
  if (configObject == null) {
    init();
  }
  return dataZones[datazone].websocket.bind;
};

module.exports.getWebSocketConnect = function(datazone) {
  if (configObject == null) {
    init();
  }
  return dataZones[datazone].websocket.connect;
};

module.exports.getMediaBind = function(datazone) {
  if (configObject == null) {
    init();
  }
  return dataZones[datazone].media.bind;
};

module.exports.getMediaConnect = function(datazone) {
  if (configObject == null) {
    init();
  }
  return dataZones[datazone].media.connect;
};

module.exports.getZMQBind = function(datazone) {
  if (configObject == null) {
    init();
  }
  return dataZones[datazone].zmq.bind;
};

module.exports.getZMQConnect = function(datazone) {
  if (configObject == null) {
    init();
  }
  return dataZones[datazone].zmq.connect;
};
