// Generated by CoffeeScript 1.3.3
var GetSender, coreClass, mediaAgent, _MediaAgent,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  _this = this;

GetSender = require('./sender_pool').getSender;

coreClass = (function() {
  var _instance;

  function coreClass() {}

  _instance = void 0;

  coreClass.get = function() {
    return _instance != null ? _instance : _instance = new _MediaAgent;
  };

  return coreClass;

})();

_MediaAgent = (function() {

  function _MediaAgent() {
    this.deleteMedia = __bind(this.deleteMedia, this);

  }

  _MediaAgent.prototype.deleteMedia = function(media_zone, media_id, next) {
    var message, sender,
      _this = this;
    try {
      sender = GetSender(media_zone);
      message = {
        method: "deleteMedia",
        data: {
          media_id: media_id
        }
      };
      return sender.send(message, function(err, res) {
        if (err != null) {
          return next(err);
        }
        return next(null, res);
      });
    } catch (e) {
      return next(e);
    }
  };

  return _MediaAgent;

})();

/*
# Modulereturn Exports
*/


mediaAgent = coreClass.get();

module.exports.deleteMedia = function(media_zone, media_id, next) {
  return mediaAgent.deleteMedia(media_zone, media_id, function(err, res) {
    if (next != null) {
      return next(err, res);
    }
  });
};
