// Generated by CoffeeScript 1.3.3
var Datazones, ZMQSender, getSender, senders;

Datazones = require('tern.data_zones');

ZMQSender = require('tern.zmq_helper').zmq_sender;

senders = {};

getSender = function(data_zone) {
  var endpoint, host, port, _ref;
  if (senders[data_zone] == null) {
    _ref = Datazones.getZMQConnect(data_zone), host = _ref.host, port = _ref.port;
    endpoint = "tcp://" + host + ":" + port;
    console.log('endpoint', endpoint);
    if (endpoint == null) {
      throw Err.ArgumentUnsupportedException("" + data_zone + " does not exist");
    }
    senders[data_zone] = new ZMQSender(endpoint);
  }
  return senders[data_zone];
};

module.exports.getSender = getSender;
