// Generated by CoffeeScript 1.3.3
var getPattern, ipPattern;

getPattern = function() {
  var ip, octet, quad;
  octet = '(?:25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9][0-9]|[0-9])';
  ip = '(?:' + octet + '\\.){3}' + octet;
  quad = '(?:\\[' + ip + '\\])|(?:' + ip + ')';
  return new RegExp('(' + quad + ')');
};

ipPattern = getPattern();

module.exports.verify = function(ipAddress) {
  return ipPattern.test(ipAddress);
};
