// Generated by CoffeeScript 1.3.3
/*
# Creates a string with the same length as `numSpaces` parameter
*/

exports.indent = function(numSpaces) {
  return new Array(numSpaces + 1).join(' ');
};

/*
# Gets the string length of the longer index in a hash
*/


exports.getMaxIndexLength = function(input) {
  var k, maxWidth;
  maxWidth = 0;
  for (k in input) {
    if (k.length > maxWidth) {
      maxWidth = k.length;
    }
  }
  return maxWidth;
};
