// Generated by CoffeeScript 1.3.3
var ContentTypes, SupportedContentType,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

ContentTypes = {
  'image/png': 'png',
  'image/jpeg': 'jpg',
  'image/gif': 'gif',
  'audio/mpeg': 'mp3',
  'video/h264': 'mp4',
  'video/mp4': 'mp4',
  'video/quicktime': 'mov',
  'video/x-m4v': 'm4v'
};

SupportedContentType = Object.keys(ContentTypes);

module.exports.isSupported = function(contentType) {
  return __indexOf.call(SupportedContentType, contentType) >= 0;
};

module.exports.all = SupportedContentType;
