// Generated by CoffeeScript 1.3.3
var Counter, pad;

pad = function(value, length) {
  var padArray, strValue;
  padArray = ['', '0', '00', '000', '0000', '00000', '000000'];
  strValue = value.toString();
  return padArray[length - strValue.length] + strValue;
};

Counter = (function() {

  Counter._startDate = +(new Date('2012-01-01Z'));

  Counter._pid = pad(process.pid, 5);

  Counter.counterToDate = function(counter) {
    var datePart;
    datePart = +counter.slice(0, 11) + Counter._startDate;
    return new Date(datePart);
  };

  function Counter() {
    this.lastMSec = 0;
    this.counterInMSec = 0;
    return;
  }

  Counter.prototype.next = function() {
    var currentMSec;
    currentMSec = +(new Date) - Counter._startDate;
    if (currentMSec === this.lastMSec) {
      this.counterInMSec++;
    } else {
      this.lastMSec = currentMSec;
      this.counterInMSec = 0;
    }
    return this.lastMSec.toString() + Counter._pid + pad(this.counterInMSec, 3);
  };

  return Counter;

})();

module.exports = Counter;
