// Generated by CoffeeScript 1.3.3
var BrokersHelper, Log, StatsD, initialize, internals;

Log = require("tern.logger");

BrokersHelper = require('tern.central_config').BrokersHelper;

/*
# We wrapped node-statsd here
*/


StatsD = new require('tern.statsd');

/*
# Internal variables
*/


internals = {
  statsd: null,
  configObj: null,
  config: null
};

/*
# Initialization
*/


initialize = (function() {
  internals.configObj = BrokersHelper.getConfig('perfCounter');
  if (internals.configObj != null) {
    internals.config = internals.configObj.value;
    internals.configObj.on('changed', function(oldValue, newValue) {
      console.log('perfCounter config changed');
      internals.config = newValue;
      return internals.statsd = new StatsD(internals.config.host, internals.config.port);
    });
  } else {
    internals.config = {
      host: 'localhost',
      port: 8125
    };
  }
  return internals.statsd = new StatsD(internals.config.host, internals.config.port);
})();

exports.increment = function() {
  return internals.statsd.increment.apply(internals.statsd, arguments);
};

exports.decrement = function() {
  return internals.statsd.decrement.apply(internals.statsd, arguments);
};

exports.timing = function() {
  return internals.statsd.timing.apply(internals.statsd, arguments);
};

exports.gauges = function() {
  return internals.statsd.gauges.apply(internals.statsd, arguments);
};

exports.update_stats = function() {
  return internals.statsd.update_stats.apply(internals.statsd, arguments);
};
