// Generated by CoffeeScript 1.3.3
var RedisStore, redis;

redis = require("redis");

module.exports = RedisStore = (function() {

  function RedisStore(options) {
    var _base, _ref;
    this.options = options != null ? options : {};
    this.client = redis.createClient((this.options.port != null) || 6379, (this.options.host != null) || 'localhost', {
      enable_offline_queue: false
    });
    if ((_ref = (_base = this.options).bucket) == null) {
      _base.bucket = 'queueServer-store';
    }
    this.client.select((this.options.dbid != null) || 0, function(err) {
      if (err != null) {
        throw new Error(message);
      }
    });
  }

  RedisStore.prototype.write = function(key, data, next) {
    return this.client.hset(this.options.bucket, key, data, next);
  };

  RedisStore.prototype.read = function(key, next) {
    return this.client.hget(this.options.bucket, key, next);
  };

  RedisStore.prototype["delete"] = function(key, next) {
    return this.client.hdel(this.options.bucket, key, next);
  };

  RedisStore.prototype.keys = function(next) {
    return this.client.hkeys(this.options.bucket, next);
  };

  return RedisStore;

})();
